### ISSUE TITLE
Caching searches may be dangerous -- should be off by default? 

### ISSUE THREAD

**Issue by FabioLuporini** [c0fec0de/anytree#100]
in [our project](https://github.com/opesci/devito) we use `anytree` to build abstract syntax trees. The leaves of our trees contain symbolic objects, which in turn carry data (think of it as numpy array, which can be pretty big). 

This leads to memory leaks -- when such symbolic objects disappear from user code, one would expect that the corresponding data is freed, but now with the newest `anytree` this isn't the case. Our CI caught this issue. 

Any thoughts ?

**Comment by c0fec0de** [comment]
I guess uninstalling clru_cache is not an option for you. 
I will provide a fix within the next hours.

**Comment by c0fec0de** [comment]
Thanks for the feedback.
Cached search got its own API now. https://anytree.readthedocs.io/en/2.7.1/api/anytree.cachedsearch.html
Normal search is not cached. As in the old days.

**Comment by FabioLuporini** [comment]
Thanks a lot for the fix -- it was super quick!

Yes, I can confirm on my side the issue has disappeared: `anytree 2.7.1.` is now pulled and our CI is back to green.
