### ISSUE TITLE
anchestors should be renamed to ancestors - remove anchestors

### ISSUE THREAD

**Issue by Odelya** [c0fec0de/anytree#11]
Looks like a typo

**Comment by c0fec0de** [comment]
It is already fixed in the latest version.
The `Node.anchestors` attribute will be removed in version 3.0.0.

**Comment by Odelya** [comment]
1. why would it be closed?
2. see method documentation still says anchestors

**Comment by c0fec0de** [comment]
Thanks. I have overseen the documentation. Fixed.
Let's keep the ticket open until 3.0.0. I will remove the anchestors attribute then...

**Comment by Odelya** [comment]
but why to remove the attribute? it is useful

**Comment by c0fec0de** [comment]
Please use `Node.ancestors` instead ;-) 
Node.anc**h**estors will be removed
