### ISSUE TITLE
New (?) way to iterate a tree

### ISSUE THREAD

**Issue by TomLav** [c0fec0de/anytree#120]
Hei all,

First of all thank you so much for anytree. I stumbled upon it this afternoon and could produce useful trees in no time. Very intuitive.

Now I have a tree and want to iterate upon it, but I do not find the iterator I would need in the doc (https://anytree.readthedocs.io/en/2.8.0/api/anytree.iterators.html).

Here is what I am looking for:
```
>>> f = Node("f")
>>> b = Node("b", parent=f)
>>> a = Node("a", parent=b)
>>> d = Node("d", parent=b)
>>> c = Node("c", parent=d)
>>> e = Node("e", parent=d)
>>> g = Node("g", parent=f)
>>> i = Node("i", parent=g)
>>> h = Node("h", parent=i)
>>> print(RenderTree(f, style=AsciiStyle()).by_attr())
f
|-- b
|   |-- a
|   +-- d
|       |-- c
|       +-- e
+-- g
    +-- i
        +-- h
>>> [node.name for node in NewIter(f)]
[['f','b','a'],['f','b','d','c'],['f','b','d','e'],['f','g','i','h']]
```
I am using anytree to store trajectories: a position record (the root) can move to different locations, each node being an intersection. Now I want to access all the full trajectories from the root to any leaf.

Could you please advise:
1) if this already exists, how ?
2) if it does not exist yet, does it sound complicated to contribute (remember, total anytree newbie here).

Thanks,
Thomas

**Comment by jkbgbr** [comment]
Hi,

you can try it this way:

_leaves = f.leaves
_path = _leaves[0].path
print([x.name for x in _path])
['f', 'b', 'a']

Cheers
Gábor

**Comment by c0fec0de** [comment]
Hi,

thanks.
I think what you need is a `PreOrderIter` which just returns the leave nodes and on every leaf node, you want to have the path from root:
```
>>> def iter_fulltrajectories(root):
...     for node in PreOrderIter(root, filter_=lambda node: node.is_leaf):
...         yield [node.name for node in node.path]

>>> print(list(iter_fulltrajectories(f)))
[['f', 'b', 'a'], ['f', 'b', 'd', 'c'], ['f', 'b', 'd', 'e'], ['f', 'g', 'i', 'h']]
```
If you like to implement it as true iterator, I recommend to return the entire node, not just the name
```
>>> class NewIter(PreOrderIter):
...     def __next__(self):
...         while True:
...             node = super().__next__()
...             if node.is_leaf:
...                 return node.path
>>> print(tuple(NewIter(f)))
((Node('/f'), Node('/f/b'), Node('/f/b/a')), (Node('/f'), Node('/f/b'), Node('/f/b/d'), Node('/f/b/d/c')), (Node('/f'), Node('/f/b'), Node('/f/b/d'), Node('/f/b/d/e')), (Node('/f'), Node('/f/g'), Node('/f/g/i'), Node('/f/g/i/h')))
```
If this solves your use-case, please close the ticket.

HTH
Daniel
