### ISSUE TITLE
How do I use an actual variable as a variable?

### ISSUE THREAD

**Issue by daniellelaforte** [c0fec0de/anytree#124]
Let's say I have:
```
def main():
    for tag in tags['data']:
        if "parentTag" not in tag:
            tag['id'] = Node(tag['name'])
            top = tag['id']
            break
    for tag in tags['data']:
        if "parentTag" in tag:
            print(tag['parentTag']['id'], top)
            if (tag['parentTag']['id'] == top):
                tag['id'] = Node(tag['name'], parent=top)

    for pre, fill, node in RenderTree(top):
        print("%s%s" % (pre, node.name))

if __name__ == "__main__":
    main()
```
I can't do this:   if (tag['parentTag']['id'] == top): 
because top now is not the "34533" I was looking for, it is instead equal to Node('/something here')). I need it to act as the variable it is. What should I do?

**Comment by c0fec0de** [comment]
* Can you please provide your data `tags`
* What is the intend of your code?

**Comment by daniellelaforte** [comment]
It doesn't matter for my question. What I am trying to say is if I make a variable like this:
"54" = Node("Udo")
top = "54"
and then I print this:
print(top) I get the path of the Node
but what if I actually want to print out "54"? I can no longer do that.

**Comment by c0fec0de** [comment]
* "54" is not a valid variable name
* a node is just an instance of the class `Node`
* if you want to have another node "54" please use `Node('54')` and store it in a variable `node54`
```
node54 = Node('54')
```
