### ISSUE TITLE
dynamically naming variables using string that are numbers

### ISSUE THREAD

**Issue by peterhorvat** [c0fec0de/anytree#129]
![image](https://user-images.githubusercontent.com/26047865/75333175-f3a82880-5885-11ea-8cc0-3997e36bea92.png)

here key is a number and val is a list of string numbers
example: 1 : ['2','3','4']

**Comment by c0fec0de** [comment]
Can you provide a little bit more context. What is is your issue? What do you expect?

**Comment by c0fec0de** [comment]
Please provide more context and re-open.
