### ISSUE TITLE
Add attribute for accessing the size of a tree

### ISSUE THREAD

**Issue by uduse** [c0fec0de/anytree#130]
Correct me if I missed anything. One may access a tree's `height`, `depth` but not `size`. Is there a reason for this? Or we just don't have it?

Also, it might be a good idea to overload `__len__` as well as a synonym for `size`.

**Comment by c0fec0de** [comment]
Good catch. I added at size attribute.

As the `NodeMixin` class does not implement any magic methods, i do not want to add `__len__`.
For the `Node` and `AnyNode` classes it might make sense. But as the size is already there it currently hesitate to add it. But i think about it.
I will release the next version soon, so .size will be in any case.
