### ISSUE TITLE
Make anytrees copyable

### ISSUE THREAD

**Issue by AMNeumann** [c0fec0de/anytree#131]
using `copy.deepcopy` on a tree fails with the error message `TypeError: can't pickle _thread.RLock objects`. This could be resolved by implementing the `__deepcopy__()` method on NodeMixin, copying only picklable objects and setting the others to sensible default values.

**Comment by c0fec0de** [comment]
Will take care.

**Comment by AMNeumann** [comment]
Damn, I wrote a minimum viable example:

```
from anytree import Node, RenderTree
from copy import deepcopy

a = Node('a')
b = Node('b', parent=a)
c = Node('c', parent=a)

d = deepcopy(a)
print(RenderTree(d))
```

I can't seem to reproduce the issue anymore. Seems like I missed one of my own NodeMixin descendents.

**Comment by c0fec0de** [comment]
ok - thanks

**Comment by AMNeumann** [comment]
The issue was that one of my nodes had its own logger, which was not even necessary.

**Comment by AMNeumann** [comment]
So, I have a `logging.Logger` in one of my nodes. This is obviously not the best idea in this case.
