### ISSUE TITLE
RenderTree: customize to not render some attributes

### ISSUE THREAD

**Issue by ieipi** [c0fec0de/anytree#132]
by default, RenderTree will render all attributes of the node;
can you add feature to support customize to not render/print some attributes.
the scenario is like I have add a pandas DataFrame object as attribute of the node, and i do not want it to be print any time since the dataframe has numerous data which is verbose.

**Comment by c0fec0de** [comment]
Please make use of the `nodeattrfunc`. There are several examples in the [documentation](https://anytree.readthedocs.io/en/latest/exporter/dotexporter.html#dot-exporter)
