### ISSUE TITLE
TreeError: Parent node 'word' is not of type 'NodeMixin'.

### ISSUE THREAD

**Issue by vineeth567** [c0fec0de/anytree#134]
Hi, 
I am trying to use this library to create visualisation for beam search. 
And the sample code is as follows:

```
x=['hi','hello','salut']
y=['how','are','you']
hi=Node('home')
for i in x:
    for j in y:
        j=Node(j,parent=i)
```

I want each of the elements in y are elements of x. But the error says  `TreeError:` Parent node 'hi' is not of type 'NodeMixin'.
Any suggestions to solve this issue?

**Comment by TimHe95** [comment]
```
x=['hi','hello','salut']
y=['how','are','you']
hi=Node('home')
for i in x:
    i = Node(i)
    for j in y:
        j=Node(j,parent=i)
```

**Comment by c0fec0de** [comment]
This should solve your issue. Right?
