### ISSUE TITLE
【BUG Confirmed】Visualization not right

### ISSUE THREAD

**Issue by TimHe95** [c0fec0de/anytree#135]
if I have a tree with 2 nodes that have the same name:
```
marc = Node("Marc") # root
lian = Node("lian ", parent=marc) # child
marc2 = Node("Marc", parent=lian) # grandchild

DotExporter(marc).to_picture("marc.png")
```
### It should be:
```
Marc
└── lian 
    └── Marc
```
###  But it actually is:
![image](https://user-images.githubusercontent.com/18543932/79139137-5464d380-7de8-11ea-875c-f97e511abc27.png)

###  Suggest to fix:
Maybe we should not use node name as ID when using `graphviz ` to draw the picture.

**Comment by c0fec0de** [comment]
Please make use of the 
[UniqueDotExporter](anytree.readthedocs.io/en/latest/exporter/dotexporter.html#anytree.exporter.dotexporter.UniqueDotExporter). This should address your issue.

**Comment by micuda** [comment]
@c0fec0de Link you provided does not work, @TimHe95 follow these one [UniqueDotExporter](https://anytree.readthedocs.io/en/latest/exporter/dotexporter.html#anytree.exporter.dotexporter.UniqueDotExporter). =)

**Comment by c0fec0de** [comment]
Changed README and documentation start page to make use of UniqueDotExporter
