### ISSUE TITLE
Doc: warning of reference not found

### ISSUE THREAD

**Issue by Jerry-Ma** [c0fec0de/anytree#136]
https://github.com/c0fec0de/anytree/blob/d63289b65644c6e8c9c1d83d339c2c235d9ecc31/anytree/node/nodemixin.py#L218

The above line causes the following warning when sphinx nitpick mode is enabled:

```
writing output... [100%] index
/....ComponentTemplate.children:41: WARNING: 'any' reference target not found: TreeError
```

**Comment by c0fec0de** [comment]
Will fix it.

**Comment by c0fec0de** [comment]
Fixed
