### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by mishraanoopam** [c0fec0de/anytree#14]
I think that a search function should be added to this module. It will search in all the nodes and then return the path of all the nodes (as a list) which match the given text. I have already made this function, I would like to contribute to this module.

**Comment by c0fec0de** [comment]
How does your search function look like. Can you please share?

A search typically filters out a set of nodes on a node attribute value. Various orders are possible on a tree. This is what the iterators are for. If you use the `filter_` attribute, the iterator returns just the requested nodes. Please see also [PostOrder Iterator Documentation](http://anytree.readthedocs.io/en/latest/apidoc/anytree.iterators.html#anytree.iterators.PostOrderIter). If you want to store the search result, just cast the iterator to a `tuple()` or `list()`

    found = tuple(PostOrderIter(rootnode, filter_=lambda n: n.name not in ('e', 'g')))

HTH
