### ISSUE TITLE
Add a frontend for it?

### ISSUE THREAD

**Issue by SongminYu** [c0fec0de/anytree#143]
Thanks for developing this package! It's very helpful. I am using this package to organize a tree like this:

Udo
├── Marc
│   └── Lian
└── Dan
    ├── Jet
    ├── Jan
    └── Joe

But it's very large, with many layers. So, it's a bit complicated to follow the structure. I want to ask if it's possible to add a simple frontend to present the tree: by clicking a small triangle of each node, its subnodes can be shown or folded.

It would help a lot!

**Comment by c0fec0de** [comment]
Hi,

This implies the use of a gui toolkit and other things which exceed the intend of this library. So i will not add things like that.

Feel free to create a project which uses anytree and the GUI toolkit of your choice.
