### ISSUE TITLE
API stability - pre/post attach/detach

### ISSUE THREAD

**Issue by jkbgbr** [c0fec0de/anytree#144]
Hi,

I use the _pre_attach hook to do a preliminary check on some attributes of the attached node that is subclassed from the NodeMixin class.

#28 Deals with and explains why the _pre/_post attach/detach methods are protected.

The only question remaining for me is: can we consider the methods to be part of the stable API or is it somethoing that may change in the future - as it is usually advised, e.g. protected members may be subject to compatibility-breaking changes?

Cheers,
Gábor

**Comment by c0fec0de** [comment]
Yes. These methods are part of the stable API. They are not intended to be changed in the future.

**Comment by jkbgbr** [comment]
Great, thank you.
