### ISSUE TITLE
module 'six' has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by Giteq** [c0fec0de/anytree#146]
When trying to run unittests on my code got the following error:

AttributeError: module 'six' has no attribute 'python_2_unicode_compatible'

It seems like your're using the 1.8.0 version of six package and according to this:
https://stackoverflow.com/questions/43527538/cannot-import-six-python-2-unicode-compatible-in-django-application
python_2_unicode_compatible function is available from 1.9.0

**Comment by c0fec0de** [comment]
i will fix the deps
