### ISSUE TITLE
Sampling tree leaves

### ISSUE THREAD

**Issue by dzieciou** [c0fec0de/anytree#149]
I found an algorithm for sampling tree leaves:

> Rosenbaum, Paul R. "Sampling the leaves of a tree with equal probabilities." Journal of the American Statistical Association 88.424 (1993): 1455-1457.

It is particularly good when a tree has leaves of different depths. Does anytree support that or is there a library based on anytree that supports that?

**Comment by c0fec0de** [comment]
Hi,

i do not know the article and have no access to it.

anytree serves various tree iteration algorithms: https://anytree.readthedocs.io/en/latest/api/anytree.iterators.html 
These iterators just serve every node according to their iteration strategy. The filter argument can be used to reduce the output to leave nodes only. 

I cannot relate the article to that. Any ideas or improvements are welcome

**Comment by c0fec0de** [comment]
Close due to missing feedback - please re-open the ticket if you have input.
