### ISSUE TITLE
2 Parents

### ISSUE THREAD

**Issue by adamcunnington** [c0fec0de/anytree#151]
Cool project!

I want to use anytree to help me render a family tree / genealogy.

This means I need the notion of 2 parents. Ideally dotted lines for spouses too... but this could be derived I suppose.

I don't think anytree supports 2 parents out the box - is there some customisation I could make or is this too systemic?

**Comment by c0fec0de** [comment]
Each node just has one parent, as it is a tree node. You can use a helper class to circumvent this "limitation".

Please see https://anytree.readthedocs.io/en/2.8.0/tricks/multidim.html
