### ISSUE TITLE
delete a node

### ISSUE THREAD

**Issue by v7ai** [c0fec0de/anytree#152]
Hi,
have not found any reference on how to delete a node from a tree.
Have tried del but did not work,

Thank

**Comment by c0fec0de** [comment]
Just set the parent attribute of the node to be deleted to `None`. In this case, it is removed from its parent and from the tree the parent belongs to.

**Comment by argel1200** [comment]
Second time I've had to look this up. Would be really great to have a `node.delete()` function, or if possible, have `del node` work

**Comment by MediaEU** [comment]
> 

I don't think that this is a good idea. Anytree is just fine how it is, it has everything that's needed. Everything else I would consider as bloated. You could do your own delete function and sets parent to None.
