### ISSUE TITLE
__children and nodemixin

### ISSUE THREAD

**Issue by alex4747-pub** [c0fec0de/anytree#154]
I have a custom hierarchical tree, we wanted anytree read api to be available for this tree, I added NodeMixin. I added 'children' property with proper interface and I already had proper parent, everything works.

 But every node has is_leaf True, because it is relying on __children being present and that it is a list.

**Comment by c0fec0de** [comment]
* Please ensure to use NodeMixin as parent class
* Do not add a `children` or `parent` attribute on your child class.
* See https://anytree.readthedocs.io/en/latest/api/anytree.node.html#anytree.node.nodemixin.NodeMixin for reference

**Comment by alex4747-pub** [comment]
My class is derived from NodeMixin it has iterable class children specifically to work with node list and it works 99.9%, all you have to do is to change how  is_leaf is checked from list to iterable.

**Comment by c0fec0de** [comment]
Can you please provide a minimal example?

**Comment by c0fec0de** [comment]
No details provided
