### ISSUE TITLE
How to return path based on specific attribute?

### ISSUE THREAD

**Issue by k3kc** [c0fec0de/anytree#158]
I'm using a custom class with NodeMixin. There is a convenient resolution method for custom attribute paths using Resolver(pathattr='name'). But how to do the opposite - return path of a specific node based on custom attribute? Something like CustomNode.path(pathattr='name')?

**Comment by c0fec0de** [comment]
Please try:
```
from anytree import NodeMixin

class MyNode(NodeMixin):

    def __init__(self, parent=None, foo=None):
        self.parent=parent
        self.foo = foo

    @property
    def mypath(self):
        return "/".join(str(p.foo) for p in self.path)


udo = MyNode(foo=0)
marc = MyNode(parent=udo, foo=1)
lian = MyNode(parent=marc, foo=2)

print(udo.mypath)
print(marc.mypath)
print(lian.mypath)
```
Will create:
```
0
0/1
0/1/2
```

**Comment by k3kc** [comment]
Thanks, I came up with a similar solution, just wanted to check if there was a built-in method that I overlooked.
