### ISSUE TITLE
Determination of direct children counts

### ISSUE THREAD

**Issue by elfring** [c0fec0de/anytree#160]
I would like to determine the number of direct children (for non-leaf nodes).
I imagine that unique identifiers will be needed then as references for relevant nodes.
But [the tree iteration](https://anytree.readthedocs.io/en/2.8.0/api/anytree.iterators.html "Programming interfaces for tree iteration") is working with the attribute “name” (which might not be unique) so far.
Thus I imagine also that the usage of paths would become helpful (so that an auxiliary node attribute can be avoided as long as pointer alternatives would not be applicable).

Will a configurable formatting become relevant for the display and further data processing of the calculated counts?

**Comment by JuliaLawall** [comment]
I have no idea what this is asking about.  Nodes in what?  The AST? The CFG? Something else?  This is not appropriate for Coccinelle.  If you want to use the Coccinelle AST or CFG to write a visitor in OCaml, go ahead.

**Comment by elfring** [comment]
>I have no idea what this is asking about.

I imagine that you can contribute a bit more help according to your experiences from various knowledge areas.

[The general data structure “tree”](https://en.wikipedia.org/wiki/Tree_(data_structure) "Description for data processing with trees") triggers some software development challenges.
One of them is to count children based on known selection criteria.
:thinking: How do you think about to clarify possibilities for counting?

If nodes should be adjusted in-place, unique references would be needed for involved objects.

**Comment by JuliaLawall** [comment]
On Thu, 1 Apr 2021, Markus Elfring wrote:

>
>       I have no idea what this is asking about.
>
> I imagine that you can contribute a bit more help according to your experiences from various knowledge areas.
>
> The general data structure “tree” triggers some software development challenges.
> One of them is to count children based on known selection criteria.
> 🤔 How do you think about to clarify possibilities for counting?
>
> If nodes should be adjusted in-place, unique references would be needed for involved objects.

Maybe what yyou want is the number of statements + the number of
expressions.

julia

**Comment by elfring** [comment]
>Maybe what yyou want is the number of statements + the number of expressions.

* Another answer depends on views for a specific software development task at the moment.
* It seems that we are still trying to achieve a better common understanding also according to [the use case “Replacing #define directives with the help of SmPL”](https://lore.kernel.org/cocci/alpine.DEB.2.22.394.2103281644480.2854@hadrien/ "Clarification attempt").

**Comment by JuliaLawall** [comment]
On Fri, 2 Apr 2021, Markus Elfring wrote:

>
>       Maybe what yyou want is the number of statements + the number of expressions.
>
>  *  Another answer depends on views for a specific software development task at the moment.
>  *  It seems that we are still trying to achieve a better common understanding also according to the use case “Replacing #define directives with the help of SmPL”.

I don't see why you would want the number of children of an AST to remoace
#defined with enums.

julia

**Comment by elfring** [comment]
>I don't see why you would want the number of children of an AST to remoace #defined with enums.

:thinking: I imagine that a few macros can be converted to [enumerations](https://en.cppreference.com/w/c/language/enum "Documentation") if their identifiers share (prefix) patterns.
I presented a conversion approach where such identifiers can be transformed into trees so that prefixes (or key words) which will occur more than once can be determined in a systematic way.

**Comment by JuliaLawall** [comment]
On Fri, 2 Apr 2021, Markus Elfring wrote:

>
>       I don't see why you would want the number of children of an AST to remoace #defined with enums.
>
> 🤔 I imagine that a few macros can be converted to enumerations if their identifiers share (prefix) patterns.
> I presented a conversion approach where such identifiers can be transformed into trees so that prefixes (or key words) which will occur more than once can be determined in a systematic way.

This has nothing to do with Coccinelle.  You made a data structure.
Surely you can figure out how to count the children in this data
structure.

**Comment by elfring** [comment]
>This has nothing to do with Coccinelle.

:thinking: I find that related applications can be considered and accordingly clarified.


>Surely you can figure out how to count the children in this data structure.

This is the purpose of this issue in combination with a software like “anytree”.
Do any development considerations become relevant then for [the distinction of mutable and immutable data structures](https://docs.python.org/3/reference/datamodel.html#objects-values-and-types "Documentation")?

**Comment by elfring** [comment]
Will any extensions become helpful also for [the software documentation](https://github.com/c0fec0de/anytree/blob/d63289b65644c6e8c9c1d83d339c2c235d9ecc31/anytree/node/nodemixin.py#L176 "Update candidate")?
