### ISSUE TITLE
Extend documentation for “Node.path”

### ISSUE THREAD

**Issue by elfring** [c0fec0de/anytree#162]
I find [the description for the method “path” of the class “Node”](https://github.com/c0fec0de/anytree/blob/d63289b65644c6e8c9c1d83d339c2c235d9ecc31/anytree/node/nodemixin.py#L285 "Update candidate") too terse.
I would appreciate another bit of clarification besides the shown examples.

**Comment by c0fec0de** [comment]
Fixed.
