### ISSUE TITLE
export to table functionality

### ISSUE THREAD

**Issue by jannikmi** [c0fec0de/anytree#170]
For some use cases, like storing a tree structure to a relational data base, it is required to export a created object oriented tree into a table format (with a column like parent_id linking the nodes).
It would be nice if `anytree` had a functionality like `node.to_dataframe()` for this.

**Comment by c0fec0de** [comment]
* Can you provide a more specific example.
* The proper approach would be to implement a dedicated Exporter

**Comment by kayjan** [comment]
Hi, this is implemented over here.

https://bigtree.readthedocs.io/en/latest/bigtree/tree/export.html#bigtree.tree.export.tree_to_dataframe
