### ISSUE TITLE
Delete leafs from tree

### ISSUE THREAD

**Issue by albapa** [c0fec0de/anytree#175]
I would like to delete leafs of a tree but I couldn't find a good way - is there a method that I missed? Thanks!

**Comment by jkbgbr** [comment]
Same as #183 
Nodes are removed from the tree by setting the parent to None. This will not delete the node but make it the root so afterwards you have two trees. See in the [docs](https://anytree.readthedocs.io/en/2.8.0/intro.html#basics).
