### ISSUE TITLE
A typo at the documentation of anytree

### ISSUE THREAD

**Issue by hanochIL** [c0fec0de/anytree#178]
**The documentation of anytree.search.find_by_attr**

anytree.search.find_by_attr(node, value, name='name', maxlevel=None)
Search for single node with attribute name having value but stop at maxlevel.
Return tuple with matching nodes.    **<<<< I think that there is a typo here**

It should be:
Return matching node.

**Comment by c0fec0de** [comment]
It was a typo.

Fixed.
