### ISSUE TITLE
Newick format

### ISSUE THREAD

**Issue by E-Farahbakhsh-T** [c0fec0de/anytree#179]
Hello, 

I was wondering whether there is any function that we can convert trees in Newick format to anytree or not?

Thanks 
elena

**Comment by jkbgbr** [comment]
nothing stock but you should probably be able to do this simply using [weighted edges](https://anytree.readthedocs.io/en/2.8.0/tricks/weightededges.html)

**Comment by c0fec0de** [comment]
Yes. Please use weighted edges.
