### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by splisov** [c0fec0de/anytree#180]
`anytree` version `2.8.0` supports Python versions up through 3.8.

Can a future `anytree` version support 3.9 (and/or 3.10)?

Otherwise, is there any workarounds to include this package in a 3.9 project?

**Comment by britive-thomasrawley** [comment]
Seems to be working fine in 3.9.7.

**Comment by twratl** [comment]
Seems to be working fine with 3.9.7
