### ISSUE TITLE
What options are there for nodeattrfunc in dotexporter

### ISSUE THREAD

**Issue by ondiekisteven** [c0fec0de/anytree#193]
Hi, I am trying to export data into a picture. I want it to display something like a menu. The problem is i cant figure out what options are there for nodeattrfunc, which should decorate the node. The example given shows one such option which is using ` shape=diamond`. I wanted to know what other options are available, or where I can find them. Thanks

**Comment by eckp** [comment]
DotExporter exports to the Graphviz DOT language, so there you can find an overview of all attributes:
https://www.graphviz.org/doc/info/attrs.html#h:uses

**Comment by ondiekisteven** [comment]
Thanks.
