### ISSUE TITLE
Get to a node given a path

### ISSUE THREAD

**Issue by ondiekisteven** [c0fec0de/anytree#195]
Hi, I am building a USSD application and using this library, I wanted to know if there is a way I can feed it a path and it returns the node at the path. Is there something like that or will i need to do it myself.

**Comment by whitews** [comment]
@ondiekisteven 

I have done this in one of my projects in a class method. You can find the code here:

https://github.com/whitews/FlowKit/blob/32797c0a3177278b6b8cafcb5aba9e0345f4b0f5/flowkit/_models/gating_strategy.py#L226

It takes into account that multiple paths may exist for the same node name. Maybe you've already written an implementation, but thought I'd throw it out there in case it helps.

**Comment by lverweijen** [comment]
If I understood the queestion correctly this can be done with resolver? See https://anytree.readthedocs.io/en/latest/api/anytree.resolver.html

**Comment by c0fec0de** [comment]
Please use resolver.
