### ISSUE TITLE
Make lines stright, not curve.

### ISSUE THREAD

**Issue by victorterancas** [c0fec0de/anytree#199]
**Is anyway to make the lines straight?**

In [Graphviz library](https://graphviz.org/docs/attrs/splines/) is documented with the function `splines=line` or `false`. 
![image](https://user-images.githubusercontent.com/92316283/171277723-c5077870-3066-4346-a2f4-d9f95d6df60b.png)

It is only valid on Graphs:
![image](https://user-images.githubusercontent.com/92316283/171277876-64d842fc-d24c-4e8f-ac6b-3804d4aae210.png)

I have only see this example, from the following [page](https://graphviz.readthedocs.io/en/stable/manual.html):
`n = graphviz.Digraph(name='splines', engine='neato',
                     graph_attr={'splines': 'true'},
                     node_attr={'shape': 'point'})`

But i cannot find the function "graph_attr" in `DotExporter()`. Therefore, i have to assume right now it is not possible?

Thank you 😄.

**Comment by jkbgbr** [comment]
I guess this question belongs rather to the graphviz page, doesn't it?

**Comment by c0fec0de** [comment]
The DotExporter just generates the output file and provides hook-ups to customize.
