### ISSUE TITLE
How to cite the package in scientific paper such as IEEE transaction like Scipy

### ISSUE THREAD

**Issue by ZZLLKK** [c0fec0de/anytree#201]
As title mention, citing information is available in scipy https://scipy.org/citing-scipy/. Is there any way to cite the package?

**Comment by moi90** [comment]
For SciPy, you actually cite the paper published in Nature Methods. As there is no paper about anytree, you could reference the documentation.

**Comment by c0fec0de** [comment]
There is no paper available. Please use the documentation.
