### ISSUE TITLE
Error in post-attach does not undo the operation

### ISSUE THREAD

**Issue by kayjan** [c0fec0de/anytree#208]
Taking the read-only example and implementing checks on post_attach instead of pre_attach, it does not undo the operation that is supposed to be atomic.

Sample code to replicate the issue below,

```
from anytree import NodeMixin


class SampleNode(NodeMixin):
    def __init__(self, foo, parent=None):
        super(SampleNode, self).__init__()
        self.foo = foo
        self.readonly = False
        self.parent = parent
    def _post_attach(self, parent):
        if self.root.readonly:
            raise ValueError()
    def _post_detach(self, parent):
        if self.root.readonly:
            raise ValueError()

a = SampleNode("a")
a0 = SampleNode("a0", parent=a)
a1 = SampleNode("a1", parent=a)
a1a = SampleNode("a1a", parent=a1)
a2 = SampleNode("a2", parent=a)

assert a1.parent == a

a.readonly = True
with pytest.raises(ValueError):
    a1.parent = a2

a1.parent == a2 # returns True, it should undo the operation
```

**Comment by c0fec0de** [comment]
Only the ``_pre_*`` hookups prevent the tree manipulation (see `Important` note here https://anytree.readthedocs.io/en/latest/intro.html#custom-separator) 

Will add another note, at the example.

**Comment by kayjan** [comment]
This is not an issue on `pre-` vs `post-` hookups, the example was just to simulate an error.

The issue is that any error should rollback to the previous state and undo the operation, but that is not the case.

**Comment by c0fec0de** [comment]
Got your point. 

The rollback may be complicated. It is just another operation on tree, which cause another pre/post-hookup-processing. Which might cause errors as well. And how to handle them.

My decision was to keep-it-simple. pre-hookup errors prevent the tree manipulation. post-hookups not. This is what is also clearly stated in the documentation. 

What is your exact use case for handling the post-hookup errors?

**Comment by c0fec0de** [comment]
I am aware of the try-except approach. Nevertheless, it gets quite complicated if the rollback fails too. Would like to skip for now.
