### ISSUE TITLE
Documentation example for Utilities confusing

### ISSUE THREAD

**Issue by ArneMeier** [c0fec0de/anytree#209]
I might misunderstand something, but the example for, e.g., `leftsibling` in the documentation of `anytree/util/__init__.py` states two things

1. It suggest only `from anytree import Node`
2. To directly call, e.g., `leftsibling(dan)`

For me, both did not work out. I had to
1. Import the method via `from anytree.util import leftsibling`
2. Do a, e.g., `print(leftsibling(joe))` in order to get the desired output.

**Comment by c0fec0de** [comment]
Good hint. Thanks. Improved it.

Feel free to re-open, if the new documentation does not fit your expectation.
