### ISSUE TITLE
Will there ever be support for multiple parents? 

### ISSUE THREAD

**Issue by johntiger1** [c0fec0de/anytree#21]

**Comment by jkbgbr** [comment]
As an outsider I don't think there will be ever, as a tree structure is by definition a graph without cycles. If you need multiple parents, use a module that supports general graphs.
More on this [here](https://en.wikipedia.org/wiki/Tree_(data_structure)#Definition).

**Comment by c0fec0de** [comment]
Exactly. A node has one parent at maximum. Otherwise it is not a tree. Please see also #23.

**Comment by macsir** [comment]
Actually, @johntiger1 you can use SymlinkNode to support this. Thank you @c0fec0de for the excellent development!
