### ISSUE TITLE
do you have functionality to count how many time particular branch was added

### ISSUE THREAD

**Issue by Sandy4321** [c0fec0de/anytree#210]
per
https://stackoverflow.com/questions/2358045/how-can-i-implement-a-tree-in-python

do you have functionality to count how many time particular branch was added

lets say 
marc = Node("Marc", parent=udo)
lian = Node("Lian", parent=marc)

was added 12 times , then we want to see counts ?

**Comment by c0fec0de** [comment]
If you run the code 
```python
marc = Node("Marc", parent=udo)
lian = Node("Lian", parent=marc)
```
12 times, you result in 12 trees with two nodes.

What do you want to count exactly?

Please provide more information and re-open the ticket.

**Comment by Sandy4321** [comment]
how many times same brache was added
we can add exactly the same branch many times ?
