### ISSUE TITLE
Timeline for version 3.0?

### ISSUE THREAD

**Issue by whitews** [c0fec0de/anytree#217]
Hey @c0fec0de,

Just wondering when version 3.0 will be released that supports Python up to 3.10. Looks like the main branch has support for it and I've been using version 2.8 for a while with Python versions 3.7 - 3.10 without problems. Anything you'd like help with? 

Thanks for the great work on this library!
-Scott

**Comment by c0fec0de** [comment]
Will focus on anytree this month. First focus on a 2.X and have something reasonable by end of August. Maybe earlier.
