### ISSUE TITLE
Resolver.glob on node without children gives IndexError

### ISSUE THREAD

**Issue by lverweijen** [c0fec0de/anytree#221]
Resolver.glob on node without children gives IndexError.
For non-existing paths it also seems to return nothing instead of an empty iterable, which would be preferred.
When using resolver.get instead it gives correct output instead.

```python
import anytree
node = anytree.Node("root")
resolver = anytree.Resolver()
resolver.glob(node, "/root")  # IndexError, expected [node]
resolver.glob(node, ".")  # IndexError, expected [node]
resolver.glob(node, "")  # IndexError, expected [node]
resolver.glob(node, "..")  # IndexError, expected (ResolverError or just [], but should be consistent with get)
resolver.glob(node, "root")  # Returns nothing, expected []
resolver.glob(node, "bla")  # Returns nothing, expected []
resolver.glob(node, "/bla")  # Returns nothing, expected []
```

Version used is 2.8.0

**Comment by lverweijen** [comment]
By the way, can't glob just use the standard library function `fnmatch` in the background (which gives you some features for free)?

**Comment by lverweijen** [comment]
Seems to be the same as https://github.com/c0fec0de/anytree/issues/125 (but that issue is closed)

**Comment by c0fec0de** [comment]
I agree, that the `Resolver` is a little bit too addicted to exceptions.
I will add a relax attribute, which gives expected empty list.
I will also ensure consistency between `get` and `glob`.
