### ISSUE TITLE
Join forces with bigtree

### ISSUE THREAD

**Issue by lverweijen** [c0fec0de/anytree#223]
Would it be an idea to join forces with bigtree?
I see a lot of overlap between both projects and perhaps a merger can combine the best of both worlds.
Since both have a MIT license, it might not even be that difficult.

One difference is that bigtree depends on pandas, whereas anytree is python-pure.
Maybe pandas can be made optional or even dropped if there is no performance difference.

Projects:
- [anytree](https://github.com/c0fec0de/anytree/)
- [bigtree](https://github.com/kayjan/bigtree/)

**Comment by c0fec0de** [comment]
just had limited time for anytree - sorry for that.
Will try to compensate this in August.

anytree does not have any dependencies. Which is good. So want to keep it.

**Comment by lverweijen** [comment]
See also discussion here: https://github.com/kayjan/bigtree/issues/65

For the case of `separator` in anytree. This attribute can also be made part of `Resolver` instead:

    resolver = Resolver("name", separator="/")

**Comment by c0fec0de** [comment]
anytree development continues. I will integrate some features and extend documentation.
