### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lverweijen** [c0fec0de/anytree#224]
How is the project licensed?

The about page says it is licensed as:

[Apache-2.0 license](https://github.com/c0fec0de/anytree/blob/main/LICENSE)

In the pyproject.toml it is licensed as:

    license = "MIT"

and the license file says:

    Apache License

**Comment by c0fec0de** [comment]
We will switch to MIT. 
This is just sneaked in.
will fix it

**Comment by c0fec0de** [comment]
Will stay with Apache 2.0 for now

**Comment by c0fec0de** [comment]
Fixed
