### ISSUE TITLE
Rearranging the tree

### ISSUE THREAD

**Issue by jkbgbr** [c0fec0de/anytree#23]
I'm using in one of my current projects the NodeMixin class and I quite enjoy the simple way it works. I very much appreciate the work put in the module. 
I wonder if it would be possible to extend the package to enable defining two - or possibly more - "parallel" trees from the same set of nodes to account for different logics in the nodes.
Think: all people in the world can be ordered in a family tree on a pure "biological" basis but also like "real" parents - who grew who up. Not necessarily the best example but I hope you get the point.
Current implementation uses the parent attribute as a keyword to define the parent-child relations. Would it be possible to change this to a configurable keyword and - naive thinking, without really knowing and/or having studied the inner workings of the module - use mostly getattr-setattr to do the job?

**Comment by c0fec0de** [comment]
I got your point. You want to have nodes with a `foo_parent` and a `bar_parent` attribute. This implies to have the other tree attributes duplicated in the same way `foo_children` and `bar_children`. The entire module needs to be adapted for that. There is an easier way.

Please consider to have an intermediate object with `foo` and `bar` as `NodeMixin` class instances. In this case you just need to set `foo.parent` and `bar.parent` and all tree attributes get duplicated in the same way `foo.children` and `bar.children`. The entire module will work on that base. I will add an example to the documentation.

HTH

**Comment by jkbgbr** [comment]
Would be perfect, thanks in advance!
