### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by kazet** [c0fec0de/anytree#240]
Hello,

on Github, the license is Apache/2.0. On PyPI the license is [Other/Proprietary License](https://pypi.org/search/?c=License+%3A%3A+Other%2FProprietary+License), thus brraking automatic license verification tools such as liccheck. Would it be possible to fix the PyPI license?

**Comment by c0fec0de** [comment]
Will take care later today

kazet ***@***.***> schrieb am Mi., 25. Okt. 2023, 11:50:

**Comment by c0fec0de** [comment]
Fixed
