### ISSUE TITLE
RenderTreeGraph(root).to_picture("tree.png") Not building tree

### ISSUE THREAD

**Issue by pcakhilnadh** [c0fec0de/anytree#26]
getting this error 

> FileNotFoundError: [Errno 2] No such file or directory: 'dot'

While I Run 
`RenderTreeGraph(udo).to_picture("tree.png") Not building tree`

**Comment by c0fec0de** [comment]
Please check to `graphviz` installed. 
Please check that the command `dot` is available in your command line.

**Comment by pcakhilnadh** [comment]
graphviz is installed 
but dot in not available in command line . Im using OSX . Please tell the steps to make it available on command line

**Comment by c0fec0de** [comment]
Please check that the directory path to `dot` is in your systems path variable.
Please use google how to set it. 
Add the path of the graphviz installation directory `bin` subfolder.

HTH

**Comment by armoured-moose** [comment]
It might be worth stating in docs/README bulk text that graphviz is required instead of the comment line - I didn't know if graphviz a Python dependency and only found what to do via this issue.

**Comment by pcakhilnadh** [comment]
@armoured-moose 
 I used pip3 to install graphviz. 
 But when I installed graphviz using following command, it solved my issue.

`sudo apt install graphviz`

**Comment by armoured-moose** [comment]
@pcakhilnadh 

Yep it worked for me too, I was more just recommending that the docs explicitly state that it's a requirement :)
