### ISSUE TITLE
Naming of the "detach" and "attach" slots.

### ISSUE THREAD

**Issue by KelSolaar** [c0fec0de/anytree#28]
Hi,

I wanted to start talking about the current naming convention of the *detach* and *attach* slots:

- `_pre_detach`
- `_post_detach`
- `_pre_attach`
- `_post_attach`

In theory and accordingly to [PEP 8](https://www.python.org/dev/peps/pep-0008/), the fact they start with an underscore implies for seasoned Python developers that they are part of the recognised _private_ part of the API:

> Use one leading underscore only for non-public methods and instance variables.

This is not a major problem but it makes me a bit uncomfortable.

As a side note last week when we were discussing about some of work I have done leveraging *anytree*, a co-worker asked me why the `_pre_detach` definitions in my code were named like so, told him I could not do much about it and it was the way *anytree* was exposing the hooks.

I reckon that it would be great to name them in a way that it is clear that they are part of the public API of *anytree*.

**Comment by c0fec0de** [comment]
Python has 3 levels: public (`foo`), protected (`_foo`) and private (`__foo`)
(see also http://radek.io/2011/07/21/private-protected-and-public-in-python/)

The API of a single anytree node is depicted by the public attributes (see http://anytree.readthedocs.io/en/latest/apidoc/anytree.node.html#anytree.node.NodeMixin). These attributes can be read and some of them written (i.e. `parent`). The tree house keeping is done by real private methods (i.e. `__attach` and `__detach`).

The `_{pre,post}_{detach,attach}` methods are part of the tree house keeping. But need to be overwritten by child classes. So they are protected ones. They should never be called directly by the node API user. The user shall concentrate on `parent` attribute etc. and leave the *additional* house keeping to the child class. 

Making them public, suggests the API user to call it directly. But this might destroy the additional house keeping implemented in this functions. So having them non-public is the right-choice from my perspective.

**Comment by KelSolaar** [comment]
Right, as an API consumer I was uncomfortable touching at those but it makes totally sense in the context you describe their intended usage.

Cheers,

Thomas

**Comment by jkbgbr** [comment]
Hi,

I'll use the _pre_attach hook to do a preliminary check on some attributes of the attached node that is subclassed from the NodeMixin class.

Came here to ask the same question and totally agree with the explanation. 

The only question remaining for me is: can we consider the methods to be part of the stable API or is it somethoing that may change in the future - as it is usually advised, e.g. protected members may be subject to compatibility-breaking changes?
