### ISSUE TITLE
No module named exporter

### ISSUE THREAD

**Issue by ssabetan** [c0fec0de/anytree#32]
When trying to use DotExporter to generate PNG's on Mac OS 10.12.6:

```
>>> from anytree.exporter import DotExporter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named exporter
```

```
Name: anytree
Version: 2.2.2
Name: graphviz
Version: 0.8.1
```

**Comment by c0fec0de** [comment]
Please see the real 2.2.2 documentation at http://anytree.readthedocs.io/en/2.2.2/dotexport.html

There was a documentation build issue. The 2.3.dev0 documentation was displayed as 2.2.2. 
The dot export will move to DotExporter with version 2.3.0, which will be released the next days.

Sorry for the inconvenience.

**Comment by ssabetan** [comment]
Is 2.3.0 beta/dev available somewhere for download? I would like to utilize importing from dict, and 2.2.2 does not have this functionality

**Comment by c0fec0de** [comment]
I will release release it tomorrow.

Or u download the repo and run
python setup.py install —user

**Comment by c0fec0de** [comment]
Version 2.3.0 is out
