### ISSUE TITLE
sorting when rendering a tree

### ISSUE THREAD

**Issue by deadc0de6** [c0fec0de/anytree#36]
Awesome project !!

I was wondering if there are any way to sort the children when rendering a tree ? For example let's say I'd like the children to be sorted by name (or by attribute, ...), I could pass a sorting callback function to `RenderTree` that would sort them similarly to what `sorted` does with `key`.

Thanks

**Comment by c0fec0de** [comment]
Hi,

does this documentation meet your expectations?

    from anytree import Node, RenderTree
    root = Node("root", lines=["c0fe", "c0de"])
    s0 = Node("sub0", parent=root, lines=["ha", "ba"])
    s0b = Node("sub0B", parent=s0, lines=["1", "2", "3"])
    s0a = Node("sub0A", parent=s0, lines=["a", "b"])
    s1 = Node("sub1", parent=root, lines=["Z"])

    def mysort(items):
        return sorted(items, key=lambda item: item.name)
    for row in RenderTree(root, childiter=mysort):
        print("%s%s" % (row.pre, row.node.name))
    root
    ├── sub0
    │   ├── sub0A
    │   └── sub0B
    └── sub1

**Comment by deadc0de6** [comment]
Oh my bad, didn't read the doc carefully, sorry.

That's exactly what I needed, thanks !!

**Comment by c0fec0de** [comment]
No problem ;-)
