### ISSUE TITLE
uppercase breaks Anytime

### ISSUE THREAD

**Issue by 851597064** [c0fec0de/anytree#38]
With regards to the example on http://anytree.readthedocs.io/en/latest/importer/jsonimporter.html

If you change the word "children" on line 7 into "Children" (uppercase, that is), the example will still finish with exit code 0, but no tree will be printed. Doing the same on line 10 has no effect.

**Comment by c0fec0de** [comment]
Hi,

the `children` attribute is some kind of special, it stores the child nodes. All other attributes are just stored to the node class instance at the end. So `Children` becomes just a normal attribute.

`anytree` intends to be case-sensitive. `children` (lowercase) is the one and only right name for the list of all child nodes.

HTH
