### ISSUE TITLE
Limit substree depth in export 

### ISSUE THREAD

**Issue by hkarl** [c0fec0de/anytree#42]
It would be great if it were possible to pass options to PreOrderIter in the exporter. Concretely, I'd like to limit the depth of the exported subtree, and it should be easy if it were posisble to hand-down a "maxlevel" option to PreOrderIter (I think). But since that is hard-coded, that is not trivial to do. 

Would that make sense?

**Comment by c0fec0de** [comment]
It is difficult to use the PreOrderIter directly without losing performance. But i will add a maxlevel option.

**Comment by c0fec0de** [comment]
Fixed by #119
