### ISSUE TITLE
Create tree from list of indented strings

### ISSUE THREAD

**Issue by Sup3rGeo** [c0fec0de/anytree#43]
Hi,

I am using `anytree` to generate a tree-view of pytest hooks based on a log file with indented hooks. https://github.com/pytest-dev/pytest/issues/3261

For that I needed to create a function to convert a list of indented strings to a tree. Apparently another users on stackoverflow have needed it:
https://codereview.stackexchange.com/questions/176391/parsing-indented-text-and-inserting-its-data-into-a-tree
https://stackoverflow.com/questions/17858404/creating-a-tree-deeply-nested-dict-from-an-indented-text-file-in-python
https://stackoverflow.com/questions/32101253/converting-a-string-to-a-tree-structure-in-python?rq=1

I have created the following script for doing this and it is quite simple:
https://github.com/Sup3rGeo/pytest/blob/master/doc/pytesthooks.py

I believe it makes sense to make this part of anytree as a "indented strings importer".

So if you agree I would gladly add a pull request for this. Thanks!

**Comment by c0fec0de** [comment]
Good idea to have a IndentedStringImporter class.

Please add an optional callback for creating the single node class instance as the `nodecls` attribute of the `DictImporter` does (http://anytree.readthedocs.io/en/latest/importer/dictimporter.html#module-anytree.importer.dictimporter)

Tests with 100% coverage would be highly appreciated.

**Comment by Sup3rGeo** [comment]
pull request made (#48)

**Comment by Sup3rGeo** [comment]
Hi! I see the [documentation for the feature](http://anytree.readthedocs.io/en/latest/importer/indentedstringimporter.html), but the PyPI package v2.4.3 I installed doesn't seem to have it.

**Comment by c0fec0de** [comment]
I need to release the package. The documentation got accidentally updated. I'll fix that.

**Comment by StevenLi-DS** [comment]
I think the package, but could found a easy way to costruct a tree from a list like the following: 

```
[['harry', 'jane', 'diane', 'mary'],
 ['harry', 'jane', 'mark'],
 ['harry', 'jane', 'diane', 'george', 'jill'],
 ['harry', 'bill']]
```

Maybe I missed something?
