### ISSUE TITLE
Assertion wrongly uses __eq__ for testing membership in children list

### ISSUE THREAD

**Issue by bobpepin** [c0fec0de/anytree#45]
Hi,
In my application I have a Mapping type that is also a NodeMixin. Since the Mapping redefines __eq__ to be key-wise comparison the following assertion gets triggered when two sibling nodes have the same keys and values:
`assert self in parentchildren, "Tree internal data is corrupt."`

I attached a diff to change this to use object identity comparison:
`assert any(x is self for x in parentchildren), "Tree internal data is corrupt."`

Best,
Bob
[assert.diff.txt](https://github.com/c0fec0de/anytree/files/1820935/assert.diff.txt)

**Comment by c0fec0de** [comment]
Good catch. I will extend testing and fix it.

**Comment by c0fec0de** [comment]
Just fixed it (60bc1a110ec93ea242e3c2a4182e1933bf1da10d)
A new release will be done within the next 48 hours.
