### ISSUE TITLE
Dotexporter.to_picture does not work on Windows

### ISSUE THREAD

**Issue by santacml** [c0fec0de/anytree#47]
I might not have done this correctly (submitting an issue and pull request) as it is my first time using github. Let me know if I need to fix anything!

On Windows, the current "to_picture" function does not work as the temporary file name is not visible to the system. Therefore, calling "dot" on the command line will result in a FileNotFoundError.

The fix changes the function so that on windows/cygwin, the file is not deleted until after the picture is made. Once the picture is made, the file in unlinked.

**Comment by c0fec0de** [comment]
I fixed #46
Thanks.
