### ISSUE TITLE
Can't export Node Object in Python3

### ISSUE THREAD

**Issue by Fanchao-Qi** [c0fec0de/anytree#49]
I find that I can only export Node object with Exporter in Python2. In Python3, however, I can only export AnyNode Object with Exporter and when I export Node Object, it shows _'Node' object does not support indexing_.

I hope you can fix it. Thanks!

**Comment by c0fec0de** [comment]
Can you provide an example please?

**Comment by c0fec0de** [comment]
Closed due to missing example
