### ISSUE TITLE
RenderTree output in wxPython TextCtrl

### ISSUE THREAD

**Issue by jkbgbr** [c0fec0de/anytree#50]
Probably not an anytree issue, but perhaps someone already had the same experience.
I use wxPython's TextCtrl to render my Anytree object. Everything renders nice except for the percent signs. In the example below each "115428736n" (a hash maybe?) stands / should stand for the percent sign. 

Any idea what this might be and how to fix it?

`08:23:22: └── results`
`08:23:22:     ├──   41 115428736n BF1 für Head crown, serf = 3.94 ≤ SheetThickness, 10 NW (9.5 MW).`
`08:23:22:     ├──   60 115428736n BF1 für Head knuckle, serf = 5.75 ≤ SheetThickness, 10 NW (9.5 MW).`

**Comment by c0fec0de** [comment]
Hi,

sorry no idea.
