### ISSUE TITLE
Adding Node description to DotExporter.to_picture()

### ISSUE THREAD

**Issue by kenziefc** [c0fec0de/anytree#53]
How can we display Node descriptions that has been set beforehand in DotExporter.to_picture() ?

In my case my nodes was initialised with Node("A", task="task A"), I want the task to be displayed under the node name. Something like this:

```
+--------+
|      A |
|  task A|
+--------+
```

**Comment by kohaugustine** [comment]
You can specify whatever information you want to be printed in the generated picture through the `nodeattrfunc` argument of the `DotExporter` object. In your case, I can imagine that it would be something like:

```nodeattrfunc=lambda node: 'label="{name}\n{task}"'.format(name=node.name, task=node.Task)```

the `\n` forces the task to be printed on a new line after the name, hence displaying the task under the node name.

**Comment by c0fec0de** [comment]
Guess it solved the issue
