### ISSUE TITLE
Feature Request: leaves attribute for Node objects

### ISSUE THREAD

**Issue by JoshPaterson** [c0fec0de/anytree#56]
I'm sorry if I'm overlooking a more obvious and better way to do this, but when I want to find all of the leaves of a node I have been using a list comprehension like this:

```
leaves = [node for node in root.descendants if node.is_leaf]
```
and it seems like it would be a nice feature to be able to do this:

```
leaves = root.leaves
```

Thanks for all your work on this very useful package!

**Comment by Paulo-Monteiro** [comment]
I also think that it a good idea probably adding to NodeMixin
    def leaves(self):
        return [node for node in anytree.iterators.PreOrderIter(self, filter_= lambda node: node.is_leaf)]

**Comment by c0fec0de** [comment]
c6d867d37cd1a85fa55aed4e69074cc05fd7b1a6
