### ISSUE TITLE
symbolic links

### ISSUE THREAD

**Issue by harishmk** [c0fec0de/anytree#59]
is it possible to have some kind of of support for symbolic links where a node can point/link to another part of the tree?

**Comment by c0fec0de** [comment]
Good idea.

It is possible to implement a symlink node which just delegates all item attribute access to another node, except the tree related.

There are some side-effects need to be checked. I give it a try.

**Comment by EsbenLorenzen** [comment]
Has this been implemented as a feature?

If not, could you @c0fec0de expand on how you would create a symlink node to allow this functionality?

**Comment by c0fec0de** [comment]
I just wasn't able to include it in the latest release. 
I think i will add an extra SymlinkNodeMixin class
