### ISSUE TITLE
Inconsistent state after LoopError

### ISSUE THREAD

**Issue by gregreich** [c0fec0de/anytree#6]
If a node's parent is changed, the node will be detached (i.e. its parent's children list is updated), but the parent of the corresponding node remains unchanged; if the __check_loop method now raises a LoopError which is captured, the tree becomes inconsistent and the node cannot be re-attached to its previous parent because of lines 102 to 104 in node.py:

```python
        elif parent is not value:
            # detach, check_loop, attach ...
        else:
            # keep parent
            pass
```

Therefore, I suggest to add the following line to node.py:
```python
elif parent is not value:
     # change parent node
     self.__detach(parent)
     # reset parent
     self._parent = None
     self.__check_loop(value)
     self.__attach(value)
```

Like this, a node has a defined parent after it has been detached, even if an error occurred.

Even more elegant would be 
```python
elif parent is not value:
     # reset parent
     self.parent = None
     self.__check_loop(value)
     self.__attach(value)
```
However, the former solution can be implemented in a non-intrusive way by modifying `_post_detach`.

**Comment by c0fec0de** [comment]
Good point. The implementation `__check_loop()` allows to check first before modifying. So that's my favorite approach.
