### ISSUE TITLE
Works and does not work in an python notebook (anaconda 3)

### ISSUE THREAD

**Issue by PKHG** [c0fec0de/anytree#60]
Hallo, 
Just busy programming an Binary puzzle solver. 
What works: creating the nodes of the search tree for a solution works fine directly. 
But if i put the commands in a def ...  The nodes are not to be found in command alinea of the notebook.
It is probably my missing knowledge of  ...  How to get the nodes accessibke out of the function ..
Help is apreciated

**Comment by c0fec0de** [comment]
Please add a minimal example

**Comment by PKHG** [comment]
startTree = totDeLaatsteKnoop(1)
print('\nstartTree = ', startTree)
mgResult = makeGraph('weetniet', startTree)
print('\n mgResult = ', mgResult)
for lis in mgResult:
    for knoop in lis:
        exec(knoop)
 
this works accessing all created nodes ;-)

putting it into:

def volgendeKnoop(nr):
    startTree = totDeLaatsteKnoop(1)
    print('\nstartTree = ', startTree)
    mgResult = makeGraph('weetniet', startTree)
    print('\n mgResult = ', mgResult)
    for lis in mgResult:
        for knoop in lis:
            exec(knoop)
    return mgResult

the nodes are not accessible

msgResult is e.g.
mgResult =  [["g2 = Node('g2', parent = g1)", "g3 = Node('g3', parent = g1)"], ["g4 = Node('g4', parent = g2)", "g5 = Node('g5', parent = g2)"]]

**Comment by PKHG** [comment]
Tried to give you an example  at github issues

And big thanks for reading my Issue and asking for more info ;-)

Other question, could I upload (include) a picuture.

greets van grandfather Peter (76 year young) ;-)

2018-08-03 12:29 GMT+02:00 c0fec0de <notifications@github.com>:

**Comment by PKHG** [comment]
Trying using markdown ;-)

# My problem with anytree in a Python Notebook


```python
import os
import sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)
anypath = "D:\OpaPeter\Anaconda3\Lib\site-packages"
sys.path.append(os.path.abspath(anypath))
from anytree import Node, RenderTree
from anytree.dotexport import RenderTreeGraph, DotExporter

g0 = Node('difficult one')  
g1 = Node('kopie van gg(0)', parent=g0)
g0.descendants

```

    (Node('/difficult one/kopie van gg(0)'),)


```python
def anyGraphMake( van, naar):
    nodeList = []
    result = []
    for el in naar:
        node = 'g{0:d}'.format(el)
        tmp = node + " = Node('g{0:d}', parent = g{1:d})".format(el, van)
        nodeList.append(tmp)
        exec(tmp)
    return nodeList
```

# nodes have to be built from a computed list lijke this:
```
[(1, [2, 3, 4]),
 (2, [5, 6]),
 (5, [7, 8]),
 (7, [9, 10, 11]),
 (9, [12, 13, 14]),
 (12, [15, 16]),
 (15, [17, 18]),
 (17, [19, 20, 21]),
 (19, [22, 23]),
 (22,
  "geschiedenis[22] is een fout ((False, 'geen volle puzzel', 'row(3) wrong', 'nullen=', 6, 'enen ', 4, 'deze rij= ', '0101010010'), ' endcontrol ')")]
```


```python
startTree = [(1, [2, 3, 4]),
 (2, [5, 6]),
 (5, [7, 8]),
 (7, [9, 10, 11]),
 (9, [12, 13, 14]),
 (12, [15, 16]),
 (15, [17, 18]),
 (17, [19, 20, 21]),
 (19, [22, 23]),
 (22,
  "geschiedenis[22] is een fout ((False, 'geen volle puzzel', 'row(3) wrong', \
  'nullen=', 6, 'enen ', 4, 'deze rij= ', '0101010010'), ' endcontrol ')")]
```


```python
fromNode = startTree[0][0]
print(fromNode)
toNodes = startTree[0][1]
print(toNodes)
```

    1
    [2, 3, 4]
    

```python
anyGraphMake(fromNode, toNodes)
```


    ["g2 = Node('g2', parent = g1)",
     "g3 = Node('g3', parent = g1)",
     "g4 = Node('g4', parent = g1)"]



```python
g0.descendants
```

    (Node('/difficult one/kopie van gg(0)'),
     Node('/difficult one/kopie van gg(0)/g2'),
     Node('/difficult one/kopie van gg(0)/g3'),
     Node('/difficult one/kopie van gg(0)/g4'))

```python
g2
```
    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-8-982cca81dbeb> in <module>()
    ----> 1 g2
    

    NameError: name 'g2' is not defined


# now, creating nodes outside a function works as I want it
## if the nodes are available s  gx (x an integer)


```python
nodeList = []
result = []
van, naar =  (2, [5, 6])
for el in naar:
    node = 'g{0:d}'.format(el)
    tmp = node + " = Node('g{0:d}', parent = g{1:d})".format(el, van)
    nodeList.append(tmp)
    exec(tmp)

```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-9-937bdf6ead5a> in <module>()
          6     tmp = node + " = Node('g{0:d}', parent = g{1:d})".format(el, van)
          7     nodeList.append(tmp)
    ----> 8     exec(tmp)
    

    <string> in <module>()
    

    NameError: name 'g2' is not defined



```python
nodeList = []
result = []
van, naar =  (1, [5, 6])
for el in naar:
    node = 'g{0:d}'.format(el)
    tmp = node + " = Node('g{0:d}', parent = g{1:d})".format(el, van)
    nodeList.append(tmp)
    exec(tmp)

```


```python
g5,g6
```

    (Node('/difficult one/kopie van gg(0)/g5'),
     Node('/difficult one/kopie van gg(0)/g6'))

```python
g0.descendants
```

    (Node('/difficult one/kopie van gg(0)'),
     Node('/difficult one/kopie van gg(0)/g2'),
     Node('/difficult one/kopie van gg(0)/g3'),
     Node('/difficult one/kopie van gg(0)/g4'),
     Node('/difficult one/kopie van gg(0)/g5'),
     Node('/difficult one/kopie van gg(0)/g6'))

```python
g1.children
```

    (Node('/difficult one/kopie van gg(0)/g2'),
     Node('/difficult one/kopie van gg(0)/g3'),
     Node('/difficult one/kopie van gg(0)/g4'),
     Node('/difficult one/kopie van gg(0)/g5'),
     Node('/difficult one/kopie van gg(0)/g6'))


```python
g2 = g1.children[0]
```


```python
g2
```

    Node('/difficult one/kopie van gg(0)/g2')

```python
nodeList = []
result = []
van, naar =  (2, [5, 6])
for el in naar:
    node = 'g{0:d}'.format(el)
    tmp = node + " = Node('g{0:d}', parent = g{1:d})".format(el, van)
    nodeList.append(tmp)
    exec(tmp)

```


```python
g0.descendants
```

    (Node('/difficult one/kopie van gg(0)'),
     Node('/difficult one/kopie van gg(0)/g2'),
     Node('/difficult one/kopie van gg(0)/g2/g5'),
     Node('/difficult one/kopie van gg(0)/g2/g6'),
     Node('/difficult one/kopie van gg(0)/g3'),
     Node('/difficult one/kopie van gg(0)/g4'),
     Node('/difficult one/kopie van gg(0)/g5'),
     Node('/difficult one/kopie van gg(0)/g6'))


```python

```

**Comment by PKHG** [comment]
I think the problem is solved: Peter does not know good enough to handle global and local variable (in the case as this) , 

nodeListDict = {}  #more or less global
for el in g0.descendants:
    nodeListDict[el.name] = el

makes in an (global alinea) something like this
g19 = nodeListDict['g19']
g20 = nodeListDict['g20']
g21 = nodeListDict['g21']
g22 = nodeListDict['g22']
g23 = nodeListDict['g23']

Suffices at the moment
