### ISSUE TITLE
scalability

### ISSUE THREAD

**Issue by harishmk** [c0fec0de/anytree#61]
I guess there are some scalability issue with anytree due to the linear search in most(all?) of the find operations.
A tree with 3 million nodes takes about 30-45 minutes to create compared to couple of seconds with just dict(of dicts)
i guess '_insert a child a node if no child node exists_' gets slowed down due to the linear search of child nodes.

**Comment by Ackbach** [comment]
Going from 2.7.2 to 2.7.3, there appears to be a performance degradation in creating Nodes. Did that overhead increase?

**Comment by c0fec0de** [comment]
Not that i am aware of. I will check.

Adrian C. Keister <notifications@github.com> schrieb am Mi., 18. Dez. 2019,
21:51:

**Comment by c0fec0de** [comment]
The 2.7.3 version did not include any functional changes. So the performance degradation seems to origin somewhere else.

**Comment by Ackbach** [comment]
c0fec0de: Thanks for checking in on that! I just upgraded from 2.7 to 2.8, and my tree import code got less efficient. Any ideas on why that might be? Or my bigger question is really just this: if I have data that looks like this:

parent child
A         B
A         C
B         D

etc, where a row's granularity is a parent-child relationship, and I have, say 1M rows, what is the most efficient way to import the tree and set up all the correct relationships?

Thanks!

**Comment by c0fec0de** [comment]
Please give 2.9.1 a try - should fix it. Re-open the ticket if not.

**Comment by lverweijen** [comment]
If you are looking for a dict to dict implementation, then I have made one at https://github.com/lverweijen/littletree.
It's interface isn't too different from anytree, but creating a tree of 3M nodes deep takes 15s for me on python 3.10 on a slow machine.

```python
from littletree import Node

import time

start_time = time.time()
deep_tree = Node()
deep_tree.path.create(range(3_000_000))
time = time.time() - start_time

print("time = {!r}".format(time))  # 15.6
```
