### ISSUE TITLE
Setting a node's children simultaneously

### ISSUE THREAD

**Issue by gregreich** [c0fec0de/anytree#7]
I find it sometimes useful to set the children of a node simultaneously all in one step. This is motivated by trees--or, more precisely, their interpretation--that can be invalidated by adding children sequentially; however, in order to check whether a particular set of children would result in a valid tree, I need to be able to add all children at once. Therefore, I extended this class by a setter method for the `children` attribute, as well as hooks  `_pre_detach_children`, `_post_detach_children`, `_pre_attach_children`, and `_post_attach_children`. Any interest in incorporating this?

**Comment by c0fec0de** [comment]
Ok. Instead of setting the parent attribute of the child nodes sequentially, you want to see them attached at once. None or all. Right?

Can you provide a little bit more example code of your intended application and share your change? It sounds like a reasonable case, which makes sense to implement.

**Comment by gregreich** [comment]
Exactly! Here is how I extended the NodeMixin class, which basically features a  setter and a deleter for ```children```, and the new hook functions:

```python
    @children.setter
    def children(self, children):
        """Function to simultaneously set all children of a node."""

        try:
            for child in children:
                break
        except TypeError:
            children = [children]

        self._pre_attach_children(children)

        old_children = self.children
        del self.children

        try:
            for child in children:
                assert isinstance(child, NodeMixin), "Failed to add non-node object."
                child.parent = self
            assert len(self.children) == len(children)
            self._post_attach_children(children)
        except LoopError:
            self.children = old_children
            raise LoopError

    @children.deleter
    def children(self):
        """Function to detach all children of a node."""
        children = self.children
        self._pre_detach_children(children)
        for child in self.children:
            child.parent = None
        assert len(self.children) == 0
        self._post_detach_children(children)

    def _pre_detach_children(self, children):
        """Method call before detaching from `parent`."""
        raise NotImplementedError

    def _post_detach_children(self, children):
        """Method call after detaching from `parent`."""
        pass

    def _pre_attach_children(self, children):
        """Method call before attaching to `parent`."""
        raise NotImplementedError

    def _post_attach_children(self, children):
        """Method call after attaching to `parent`."""
        pass
```

**Comment by c0fec0de** [comment]
Thanks!

I am gonna take it over in the next days and create a new release.

**Comment by gregreich** [comment]
Very cool, thank you!

By the way: I was thinking of a way to prevent one of the two assignment methods (setting parents for each child, or setting children for one parent); one way is to make the _pre_* methods raise an exception (like I did for ```_pre_attach_children``` and ```_pre_attach_children``` raising a ```NotImplementedError```), but this is slightly more delicate for preventing children from being added individually. In this case, the exception would have to be captured at different places, if the ```children```setter still makes use of the ```parent```property.

Any thoughts on this?

**Comment by c0fec0de** [comment]
Thanks for your contribution. I just merged your pull request. 
But it is critical to accept a single instance on setting and return a tuple on reading. So it is not possible to set a non iterable to .children attribute. With that change getter/setter serve the same data structure - an iterable.

If the tree data structure shall only make use of .parent or .children, a derived class should be implemented raising the `NotImplementedError`. But currently the *_{de,at}tach_children hookups are only called on use of the .children and *_{de,at}tach hookups are called on .children and .parent. This is somehow not consequent. I will think about restructuring the hookups.
