### ISSUE TITLE
RenderTree unicode

### ISSUE THREAD

**Issue by nadavb** [c0fec0de/anytree#70]
For some trees that contain unicode data I get exceptions like:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 22: ordinal not in range(128)`

Any idea why?

**Comment by c0fec0de** [comment]
Can you provide a minimal example please

**Comment by c0fec0de** [comment]
I extend the testing and everything worked. So please prove an example and re-open this ticket.
