### ISSUE TITLE
`Node.path_to` method?

### ISSUE THREAD

**Issue by danieljfarrell** [c0fec0de/anytree#72]
Give the structure,

    Node(A)
    ├── Node(B)
    │   └── Node(C)
    └── Node(D)

Is there a builtin way for find the path to a given node. For example, `Node.path_to(node: Node)`,

    from anytree import Node
    a = Node(name="A", parent=None)
    b = Node(name="B", parent=a)
    c = Node(name="C", parent=b)
    d = Node(name="D", parent=a)
    d.path_to(c)
    # (Node(D), Node(B), Node(C))

**Comment by c0fec0de** [comment]
Please use the [Walker](anytree.readthedocs.io/en/latest/api/anytree.walker.html)

```
from anytree import Walker`
Walker().walk(e, d)
```

        Returns:
            (upwards, common, downwards): `upwards` is a list of nodes to go upward to.
            `common` top node. `downwards` is a list of nodes to go downward to.

**Comment by danieljfarrell** [comment]
Well that was easier than I thought!

```python
def path_connecting(a, b):
    upwards, common, downwards = Walker().walk(a, b)
    path = upwards + (common,) + downwards
    return path
```
