### ISSUE TITLE
Can't use function anytree.util.commonancestors

### ISSUE THREAD

**Issue by vthuongt** [c0fec0de/anytree#73]
Hello,
first of all I liked to thank you for this module! It has helped me quite a bit. However I would like to use the documented function `anytree.util.commonancestors()` but was not able to import it: 

`from anytree.util import commonancestors` results in : _*** ModuleNotFoundError: No module names 'anytree.util'_  :

If I just import anytree and print some stuff:
`anytree.__version__` : '2.4.3'

`anytree.__path__`: ['C:\\Program Files\\Anaconda3\\envs\\testenv\\lib\\site-packages\\anytree']

If I open the above path, there is no util folder like in this git repo. I installed anytree via pip in a conda environment. What am I doing wrong?

**Comment by c0fec0de** [comment]
Please use 2.5.0.
There was a mismatch between documentation and source.
