### ISSUE TITLE
builder-like tree construction

### ISSUE THREAD

**Issue by MoshelDR** [c0fec0de/anytree#75]
Hi,

I really like the implementation of tree you gave and I have an improvement suggestion.
I am currently looking for a way to create a tree in one line, something like:
`
tree = Node("root", children=[
                   Node("first", children=[
                           Node("Lonely")
                   ],
                   Node("other")
           ])
`
Or something like a builder pattern structure:
`
tree = Node("root").buildChildren([
                   Node("first").buildChildren([
                           Node("Lonely")
                   ]),
                   Node("other")
           ])
`

Thanks,
MDR

**Comment by c0fec0de** [comment]
Hi,

good idea. I will add to support the next days and push a release
```
root = Node("root", children=[
    Node("a", children=[
        Node("aa")
    ]),
    Node("b")
])
```
