### ISSUE TITLE
Any possibility to represent DAGs with anytree?

### ISSUE THREAD

**Issue by nbeversl** [c0fec0de/anytree#76]
This is a beautiful and much-needed library. Do you know any way to represent acyclic graphs/trees (those having more than one root node) with anytree, or by extending it?

**Comment by c0fec0de** [comment]
A direct acyclic graph is not a tree. A DAG node has **multiple** parents. A tree node just **one**.

But i have an idea how to solve it. Just give me some time.

**Comment by nbeversl** [comment]
Yes, that's correct. Tree is not the right word, definitely DAG. Thanks for the reply and for any ideas you have.

**Comment by c0fec0de** [comment]
Not feasible within anytree. Sorry
