### ISSUE TITLE
NodeMixin - TypeError: multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by bakert** [c0fec0de/anytree#77]
Works: 2.4.3
Breaks: 2.6.0

```
>>> from munch import Munch
>>> from anytree import NodeMixin
>>> class MyClass(Munch, NodeMixin):
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: multiple bases have instance lay-out conflict
```

Where munch is https://github.com/Infinidat/munch

Googling around a bit this seems to be about conflicts in C implementations of classes on `__foo__` attributes. So I did this:

```
>>> [k for k in dir(Munch) if k in dir(NodeMixin)]
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

but it didn't make me feel much smarter.

Does this mean anything to you anytree peeps? I came here because obviously NodeMixin is meant to be mixed in so this feels like a bug rather than just a stupid thing I should not be attempting to do. Especially as it used to work until this version.

**Comment by bakert** [comment]
The Munch folks believe that it's probably because Munch derives from `dict` which uses `__slots__`. Does `NodeMixin` now use `__slots__`?

**Comment by c0fec0de** [comment]
Yes. `__slots__` has been added. Please try:
```
>>> from munch import Munch
>>> from anytree import NodeMixin
class MyNodeMixin(NodeMixin):
...     pass
>>> class MyClass(Munch, MyNodeMixin):
...     pass
```
As `__slots__` is not inherited, it might work

**Comment by bakert** [comment]
Thanks for taking a look. Sadly the above code  gives the same error. 

```
[gaghalfrunt pd] python3
Python 3.7.1 (default, Nov 28 2018, 11:51:47) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from munch import Munch
>>> from anytree import NodeMixin
>>> class MyNodeMixin(NodeMixin):
...     pass
... 
>>> class MyClass(Munch, MyNodeMixin):
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: multiple bases have instance lay-out conflict
```

**Comment by bakert** [comment]
Reading up at https://stackoverflow.com/questions/472000/usage-of-slots and https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots it sounds like including `__slots__` in something designed to be inherited from/mixed in might be something you want to revisit? I'm a total ignoramus so I'm all ears if you have any ideas other than freezing the anytree version at 2.4.3. Thanks!

**Comment by jkbgbr** [comment]
I had the same exception the other day when I tried to mix wxPython and the
NodeMixin class. Did not really expect it to work anyway, as wxPython
heavily uses the attribute name parent.

**Comment by c0fec0de** [comment]
I am not sure yet, which is the best way to go. Leave `__slots__` or remove.

**Comment by c0fec0de** [comment]
__slots__ will be removed
