### ISSUE TITLE
How to perform Depth First Search

### ISSUE THREAD

**Issue by DaemonNet** [c0fec0de/anytree#79]
Hi,

I am trying to perform depth first search on a tree I created with anytree. But reading the API I only found provisions for displaying the tree in ASCII format. Is there any possibility to walk a tree beginning from the root node and going depth first (assuming I don't know the other nodes beforehand)?

Greetings

**Comment by D-Vaillant** [comment]
If you're trying to find a specific node with a given attribute, the following should work:
```
# let f be the tree you want to search
for a in PreOrderIter(f):
    if a.name == "foobar":
        break
# and then a should be what you want
```

**Comment by c0fec0de** [comment]
I think, the PostOrderIter is the iterator you are looking for:
https://anytree.readthedocs.io/en/latest/api/anytree.iterators.html#anytree.iterators.postorderiter.PostOrderIter

The search functions are also quite helpful
https://anytree.readthedocs.io/en/latest/api/anytree.search.html

As this is no bug or feature request. I am going to close this issue.
