### ISSUE TITLE
How to remove an attribute from Node?

### ISSUE THREAD

**Issue by babca** [c0fec0de/anytree#80]
Hi all,

I'm missing in docs how to properly remove an attribute from node (Node/AnyNode).

```python
from anytree import AnyNode, RenderTree
root = AnyNode(id="root")
s0 = AnyNode(id="sub0", parent=root, foo=4, bar=109)
```
```python
>>> s0
AnyNode(bar=109, foo=4, id='root')
```

How can I remove `foo` completely with anytree?
```python
>>> s0
AnyNode(bar=109, id='root')
```

Thank you

**Comment by D-Vaillant** [comment]
Yup; using `del` should work:
```python
>>> s0
AnyNode(bar=109, foo=4, id='root')
>>> del s0.foo
>>> s0
AnyNode(bar=109, id='root')
```

**Comment by babca** [comment]
Wow, sometimes I need to think outside the box :-) Thanks.

It would be nice to include the example in the docs.
