### ISSUE TITLE
Implement an "export to SQL schema" feature

### ISSUE THREAD

**Issue by D-Vaillant** [c0fec0de/anytree#81]
This is something I'm personally looking into but I'm putting this as a feature request to document it. I'm interested in exporting trees into a database by creating a schema. What I'm thinking, right now, is just all of the instructions for making a fresh database with the columns based on AnyNode attributes.

**Comment by D-Vaillant** [comment]
Structure idea: Have an abstract SQLExportBase class which gives instructions about how to just make the database and the rows, without any sort of tree relationship.

From the SQLExportBase class there would be an AdjacencyExport and a NestedSet/MPTTExport - one uses adjacency lists to model the relationships, one uses the MPTT left/right method.

**Comment by c0fec0de** [comment]
Please provide an example

**Comment by c0fec0de** [comment]
No feedback.
