### ISSUE TITLE
AbstractIter is not quite a proper python iterator.

### ISSUE THREAD

**Issue by dluke** [c0fec0de/anytree#89]
`AbstractIter.__iter__` always returns a new iterator.
consider
```
nodes = anytree.PreOrderIter(root)
next(nodes) # returns root
for node in nodes: # new iterator is reset
    node # root again
```
This is not the expected operation of an iterator but is easily fixed.

Note that `AbstractIter.__init` returns a proper iterator and therefore 
`iter(anytree.PreOrderIter(root))` is one.

**Comment by c0fec0de** [comment]
Thanks. Will check
