### ISSUE TITLE
AnyNode on RenderTree

### ISSUE THREAD

**Issue by vsbatista** [c0fec0de/anytree#90]
Hi,
first of all, thanks for the amazing library. Very helpful.
I am not sure this is the right channel to make a question, so please let me know if there is a correct way.

My problem is: I have created a tree based on AnyNode objects. So far, so good. Works as designed. However, when I try to render such tree using anynode's custom attributes, I noted such custom attrs are not available. Eg:

```
def render_tree():
    for pre, _, node in RenderTree(tenant_tree):
        print("%sName: %s Kind: %s, TenantID: %s" % (pre, node.name, node.kind, node.tenant_id))
```

returns me a `Node object does has no attribute 'kind'`. Any ideas on how to implement that?

Thanks in advance!

**Comment by c0fec0de** [comment]
Ensure all your node objects have an attribute `kind`. Seems that this is missing on at least one of them.

As this is a python issue, i am going to close this ticket.
