### ISSUE TITLE
AttributeError: 'AnyNode' object has no attribute 'name'

### ISSUE THREAD

**Issue by anand98765** [c0fec0de/anytree#91]
Am not able to render graphviz image for AnyNode tree
Note: Working fine with Node

Cell 1:
>>> from anytree import AnyNode, RenderTree
>>> root = AnyNode(id="root")
>>> s0 = AnyNode(id="sub0", parent=root)
>>> s0b = AnyNode(id="sub0B", parent=s0, foo=4, bar=109)
>>> s0a = AnyNode(id="sub0A", parent=s0)
>>> s1 = AnyNode(id="sub1", parent=root)
>>> s1a = AnyNode(id="sub1A", parent=s1)
>>> s1b = AnyNode(id="sub1B", parent=s1, bar=8)
>>> s1c = AnyNode(id="sub1C", parent=s1)
>>> s1ca = AnyNode(id="sub1Ca", parent=s1c)

Cell 2:
>>> from anytree.dotexport import RenderTreeGraph
>>> RenderTreeGraph(root).to_picture("udo.png")

Error: AttributeError: 'AnyNode' object has no attribute 'name'

Please help me.

**Comment by c0fec0de** [comment]
Please use `Node` instead of `AnyNode`

The DotExporter needs at least a name attribute.

The doc needs to be clarified here.

**Comment by c0fec0de** [comment]
Please see https://anytree.readthedocs.io/en/latest/exporter/dotexporter.html
