### ISSUE TITLE
Is it possible to export pictures with Chinese/Unique characters

### ISSUE THREAD

**Issue by NinaTian98369** [c0fec0de/anytree#94]
Hi, I would like to save pictures in a multi-lingual way. It seems that those Chinese characters  are saved garbled. Is there a way to export tree pictures in Chinese?

Thanks a lot.

**Comment by c0fec0de** [comment]
Can you provide a testcase

**Comment by c0fec0de** [comment]
I extended the tests, and it works. 
No feedback, so i close the ticket. Please provide an example and re-open.
