### ISSUE TITLE
When exporting trees with special characters in strings to json they are replaced with unicode escape sequences

### ISSUE THREAD

**Issue by Holarctic** [c0fec0de/anytree#99]
RenderTree works as intended, tree is rendered with special characters shown.
JsonExporter replaces special characters with unicode escape sequences (eg. ž --> \u017e).

**Comment by c0fec0de** [comment]
anytree does not modify the strings. Any option given to the JsonExporter is just forwarded to json.dump.
Please see https://docs.python.org/3/library/json.html#basic-usage and https://stackoverflow.com/questions/18337407/saving-utf-8-texts-in-json-dumps-as-utf8-not-as-u-escape-sequence

Please try:
```
exporter = JsonExporter(indent=2, sort_keys=True, ensure_ascii=False)
```

The JsonExporter is nothing more than a wrapped DictExporter. You can run the `json.dumps` on your own:
```
data = DictExporter().export(node)
jdata = json.dumps(data, ensure_ascii=True)
```

Please close the ticket, if this solves your issue.
